### ISSUE TITLE
Review: EmployeeList.jsx and MonitoringReport.jsx

### ISSUE THREAD

**Issue by ethancheez** [hidoe-legistracker/hidoe-legistracker#121]
## Overview

The focus for this code review will be centered around the EmployeeList and MonitoringReport pages.    

## Review Branch

[review-3](https://github.com/hidoe-legistracker/hidoe-legistracker/tree/review-3)

## Files to review

* [EmployeeList.jsx](https://github.com/hidoe-legistracker/hidoe-legistracker/blob/review-3/app/imports/ui/pages/EmployeeList.jsx)
* [MonitoringReport.jsx](https://github.com/hidoe-legistracker/hidoe-legistracker/blob/review-3/app/imports/ui/pages/MonitoringReport.jsx)

## Checklists

* [Architecture](https://github.com/hidoe-legistracker/hidoe-legistracker/blob/review-1/checklists/architecture-checklist.md)
* [Design](https://github.com/hidoe-legistracker/hidoe-legistracker/blob/review-1/checklists/design-checklist.md)
* [JS](https://github.com/hidoe-legistracker/hidoe-legistracker/blob/review-1/checklists/js-checklist.md)
* [React](https://github.com/hidoe-legistracker/hidoe-legistracker/blob/review-1/checklists/react-checklist.md)

## Due date

9/27/2022

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by ethancheez** [comment]
## EmployeeList.jsx:

L10: Remove “stuff” in comment

## MonitoringReport.jsx:

L16: Comment mentions landing page, but not a landing page

L17, 165: JS-01: Exporting “Landing” for page “MonitoringReports”

**Comment by ecadiena** [comment]
## EmployeeList.jsx
JS-05: L20 try to avoid using underscore function
DE-05: Remove comments with "stuff' in it

## MonitoringReport.jsx
JS-05: L16 mentions landing page for monitoring report page?
RE-03: exporting Landing for MonitoringReports?
- Keep L11 consistent with the rest of the imports

**Comment by SoraTSky** [comment]
### EmployeeList.jsx
DE-05: L10, Remove "stuff" in the comment or edit to a more appropriate comment
JS-06: L20, use of lodash (underscore method). Prioritize the use of a built-in function.
ES-01: L17,18, Given ESLint warning: "Unresolved function or method fetch()"
### EmployeeList.jsx
ES-01: L94, L99, Given ESLint warning: "Element DropdownButton doesn't have required attribute title"

**Comment by ColeAmparo** [comment]
## EmployeeList.jsx 
DE-05 - L10: Remove comment mentioning "stuff" collection. 
JS-05 - L20: Avoid Underscore functions (I don't know how else you would do it though). 

## MonitoringReport.jsx
DE-05 - L16: Remove comment referring to landing page, this page is not a landing page. 
JS-01 - L17, 165: Change 'Landing' to 'MonitoringReport'.

**Comment by adamjparrilla** [comment]
### EmployeeList.jsx: 
L10, DE-05: Change comment that refers to Stuff Documents


### MonitoringReport.jsx: 
L16, DE-05: Change comment that mentions Landing Page
L17 & 165, JS-01: Rename construct and export from Landing to MonitoringReport

**Comment by ianbm** [comment]
### EmployeeList.jsx
L10: remove/update comment
L20: avoid lodash functions

### MonitoringReport.jsx
L16: remove/update comment
L17, L165: fix default export
L94: warning: missing required title attribute
L100: console warning: non-boolean attribute 'clas' returns 'true'

**Comment by larissa-tsai** [comment]
### EmployeeList.jsx
JS-05: Avoid using lodash or underscore function
DE-05: Remove unnecessary comments. Comments still references "stuff"

### MonitoringReport.jsx
JS-05: L16 relevance? comments is unclear and mentions landing page
RE-03: name for file is monitoring report but is titled landing, fix default export
ES-01: L94/99 ESLint warning, missing title attribute
