### ISSUE TITLE
Review: ChangePasswordUser.jsx and EditProfile.jsx

### ISSUE THREAD

**Issue by ethancheez** [hidoe-legistracker/hidoe-legistracker#136]
## Overview

The focus for this code review will be centered around the ChangePasswordUser and EditProfile pages.    

## Review Branch

[review-4](https://github.com/hidoe-legistracker/hidoe-legistracker/tree/review-4)

## Files to review

* [ChangePasswordUser.jsx](https://github.com/hidoe-legistracker/hidoe-legistracker/blob/review-4/app/imports/ui/pages/ChangePasswordUser.jsx)
* [EditProfile.jsx](https://github.com/hidoe-legistracker/hidoe-legistracker/blob/review-4/app/imports/ui/pages/EditProfile.jsx)

## Checklists

* [Architecture](https://github.com/hidoe-legistracker/hidoe-legistracker/blob/review-1/checklists/architecture-checklist.md)
* [Design](https://github.com/hidoe-legistracker/hidoe-legistracker/blob/review-1/checklists/design-checklist.md)
* [JS](https://github.com/hidoe-legistracker/hidoe-legistracker/blob/review-1/checklists/js-checklist.md)
* [React](https://github.com/hidoe-legistracker/hidoe-legistracker/blob/review-1/checklists/react-checklist.md)

## Due date

10/4/2022

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by ethancheez** [comment]
## ChangePasswordUser.jsx:

L73-79, 82-88: DE-01: Same lines of code, can refractor

L111, 112: JS-01: Same IDs, make a new ID for SIGN_UP_FORM_NEW_PASSWORD and SIGN_UP_FORM_CONFIRM_PASSWORD

## EditProfile.jsx:

L118-122, 125-129: DE-01: Same lines of code, can refractor

**Comment by CrisJavier** [comment]
## ChangePasswordUser.jsx

DE-01: L73-79, L82-88, Exact same code, refractor please

DE-02: L52-64, L66-93, Deeply nested if/else statements here, is it possible to reorganize this?

JS-01: L111, 112, Please make a new ID for the SIGN_UP_FORM_CONFIRM_PASSWORD and SIGN_UP_FORM_NEW_PASSWORD text fields

## EditProfile.jsx

DE-01: L118-122, 125-129: Exact same code, refractor if possible

ES-01: L39-58: ESLint warning: "Duplicated code fragment (20 lines long)"

**Comment by ColeAmparo** [comment]
## ChangePasswordUser.jsx

DE-01: L71 - 88: Can be refactored, the if/else can decide the CollectionName and then the updateMethod can come after the if/else statement. 

DE-02: L55 - 88: Contains many nested if/else statements, is it possible to reduce lines of code by using a ternary operator? 

DE-06: L75 & L84: Since the usual "err" is being used already, for the swal (SweetAlert) parameters the var "errr" is used. For readability is it possible to change errr -> "swalErr" (or something similar) to make sure that the reader doesn't get the error from the Meteor.call mixed up with the error from swal. 


## EditProfile.jsx 

JS-05: L73: Avoid using underscore if possible. 

DE-01: L80 - 92, L118 - 130: Refactor the blocks of code that use transferMethod and defineMethod to be similar to how updateMethod is used on this page. (Use the if/else to change the collectionName and then use the method afterwards.

**Comment by SoraTSky** [comment]
## ChangePasswordUser.jsx

DE-01: L73-79, 82-88: Both sections contains exact same code. Possible to refractor.


## EditProfile.jsx

ES-01: L39-58: ESLint warning: "Duplicated code fragment (20 lines long)" Exact same code as L15-34 in Profile.jsx.

**Comment by ianbm** [comment]
### ChangePasswordUser.jsx
L74-79, L83-88: similar blocks of code
L66-93: deeply nested if/else block
Console warning: Found 2 elements with non-unique id #sign-up-form-password

### EditProfile.jsx
L81-85, L89-93: similar blocks of code
L73: avoid lodash functions
L39: warning: duplicated code fragment (20 lines long)
Console warning: Each child in a list should have a unique "key" prop

**Comment by adamjparrilla** [comment]
### ChangePasswordUser.jsx: 
L73-79 & L82-88 DE-01: Same block of code that can be reduced

### EditProfile.jsx:
L81-83 & L89-91, L118-122 & L125-129 DE-01: Same block of code that can be reduced

**Comment by larissa-tsai** [comment]
### ChangePasswordUser.jsx
DE-02:  L66-80 nested conditionals, multiple if/else blocks
DE-01: L73-79 & 81-87 Duplicate code, refactor to reduce duplication

### EditProfile.jsx
DE-02: L61-106,  L114-129 nested conditionals, multiple if/else blocks
DE-01: Duplicate code per admin/user functions

**Comment by ecadiena** [comment]
### ChangePasswordUser.jsx
Console warning: Found 2 elements with non-unique id #sign-up-form-password
L73-79 & 81-87 duplicated code, can be reduced

### EditProfile.jsx
Console warning: Each child in a list should have a unique "key" prop
L114-129 duplicated code, can be reduced
