### ISSUE TITLE
Review: AddMeasure.jsx and Directory.jsx

### ISSUE THREAD

**Issue by ethancheez** [hidoe-legistracker/hidoe-legistracker#54]
## Overview

The focus for this code review will be centered around the AddMeasure and Directory pages.    

## Review Branch

[review-1](https://github.com/hidoe-legistracker/hidoe-legistracker/tree/review-1)

## Files to review

* [AddMeasure.jsx](https://github.com/hidoe-legistracker/hidoe-legistracker/blob/review-1/app/imports/ui/pages/AddMeasure.jsx)
* [Directory.jsx](https://github.com/hidoe-legistracker/hidoe-legistracker/blob/review-1/app/imports/ui/pages/Directory.jsx)

## Checklists

* [Architecture](https://github.com/hidoe-legistracker/hidoe-legistracker/blob/review-1/checklists/architecture-checklist.md)
* [Design](https://github.com/hidoe-legistracker/hidoe-legistracker/blob/review-1/checklists/design-checklist.md)
* [JS](https://github.com/hidoe-legistracker/hidoe-legistracker/blob/review-1/checklists/js-checklist.md)
* [React](https://github.com/hidoe-legistracker/hidoe-legistracker/blob/review-1/checklists/react-checklist.md)

## Due date

9/13/2022

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by ethancheez** [comment]
## AddMeasure.jsx

L56, 100: DE-01: Duplicate variable for fRef. Can refractor into one variable.

L58: Comment mentions “AddStuff”

## Directory.jsx

L98: DE-08: Can create a component for each DirectoryItem.

L7, 9: Comment/code mentions Stuff

**Comment by CrisJavier** [comment]
## AddMeasure.jsx

DE-05: L58 Comment mentions “AddStuff”

JS-07: L58 Comment should probably just be using “//” than “/*”

## Directory.jsx

DE-03: L5,6 Technically not dead code as it’s commented out but is it possible to just remove it?

JS-07: L10 Comment should probably just be using “//” than “/*”

**Comment by ecadiena** [comment]
## AddMeaure.jsx
DE-05: L58 mentions "AddStuff"
JS-05: L71, L74 uses _.find, should use built-in function if possible

## Directory.jsx
DE-01/DE-07: Refactor folder and measure code into DirectoryFolder.jsx and Measure.jsx

> DirectoryFolder.jsx: could create a FolderCollection
> Directory should map over MeasureCollection.

DE-03: L5-6 Remove commented out links

**Comment by SoraTSky** [comment]
### AddMeasure.jsx

ES-01: L87 Warning: Promise returned from swal is ignored

**Comment by ianbm** [comment]
AddMeasure.jsx:
Line 58: remove comment about 'stuff'
Lines 71, 74: avoid lodash and underscore functions

Directory.jsx:
Line 7: remove comment about 'stuff'
Line 9: change id

**Comment by adamjparrilla** [comment]
AddMeasure.jsx:
L58, DE-05: Comment references AddStuff rather than AddMeasure


Directory.jsx:
L7, DE-05: Comment references Stuff and could be changed to better suit the documents
L9, JS-01: Could LIST_STUFF be changed to describe the documents

**Comment by larissa-tsai** [comment]
### AddMeasure.jsx
JS-07: start comments with "/**"
DE-05: comments relating to AddStuff
JS-05: use of meteor underscore _.find

### Directory.jsx
JS-07: Add more comments
DE-05: comments relating to StuffItem
